spring:
  datasource:
    url: jdbc:h2:mem:mancala
#    url: jdbc:h2:file:/home/moreka/mancala_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true